const TermsOfServicePage = () => {
  return (
    <div className='container mx-auto px-4 sm:px-6 lg:px-8 py-16'>
      <div className='max-w-3xl mx-auto'>
        <h1 className='text-3xl md:text-4xl font-bold text-gray-800 mb-6'>Terms of Service</h1>
        <p className='text-gray-600 mb-4'><strong>Last Updated:</strong> 18 June 2024</p>

        <div className='space-y-8 text-gray-700'>
          <p>Please read these Terms of Service ("Terms") carefully before using our AI assistant service (the "Service") operated by Strompt ("we", "our", "us").</p>
          <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>1. Accounts</h2>
            <p>When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>2. Subscriptions and Payments</h2>
            <p>Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in advance on a recurring and periodic basis ("Billing Cycle").</p>
            <p className='mt-2'>At the end of each Billing Cycle, your Subscription will automatically renew unless you cancel it through the Stripe customer portal, which is accessible from your profile page, or by contacting us.</p>
            <p className='mt-2'>All payments are handled by Stripe. By submitting payment information, you authorize us (through Stripe) to charge the applicable fees to your designated payment method.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>3. Cancellation and Refunds</h2>
            <p>You may cancel your Subscription renewal at any time. You will continue to have access to the Service through the end of your billing period. As a general rule, all fees are non-refundable except where required by law.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>4. User Conduct and Content</h2>
            <p>You are responsible for any text, information, or other material you input into the Service ("Content"). You agree not to use the Service for any unlawful purpose or to violate any laws in your jurisdiction.</p>
            <p className='mt-2'>We do not claim ownership of your Content. However, by using the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and process your Content solely for the purpose of operating and providing the Service to you.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>5. Intellectual Property</h2>
            <p>The Service and its original content (excluding Content provided by users), features, and functionality are and will remain the exclusive property of Strompt and its licensors. The Service is protected by copyright, trademark, and other laws of both Germany and foreign countries.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>6. Disclaimer of Warranties; Limitation of Liability</h2>
            <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We do not warrant that the results obtained from the use of the Service will be accurate or reliable. The output generated by the AI is for informational purposes only and should not be considered as professional advice.</p>
            <p className='mt-2'>In no event shall Strompt, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, or other intangible losses, resulting from your use of the Service.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>7. Termination</h2>
            <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>8. Governing Law</h2>
            <p>These Terms shall be governed and construed in accordance with the laws of Germany, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>9. Changes to Terms</h2>
            <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide at least 30 days' notice prior to any new terms taking effect. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.</p>
          </section>

          <section>
            <h2 className='text-2xl font-semibold text-gray-800 mb-3'>10. Contact Us</h2>
            <p>If you have any questions about these Terms, please <a href='/contact' className='text-blue-600 hover:underline'>contact us</a>.</p>
          </section>
        </div>
      </div>
    </div>
  )
}

export default TermsOfServicePage
